### ISSUE TITLE
Error with 2022.2.3 and does not work

### ISSUE THREAD

**Issue by neildsb** [HomeAssistant-Mods/home-assistant-miele#104]
I get the following error in Core version 2022.2.3 and the integration does not work will stick with version 2022.2.2 for now

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:108
Integration: miele (documentation, issues)
First occurred: 10:35:50 am (1 occurrences)
Last logged: 10:35:50 am

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 151, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
  File "/config/custom_components/miele/__init__.py", line 108, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

**Comment by dolodobendan** [comment]
Thanks, I was tempted to do an update, but I guess I'll wait a bit.

**Comment by neildsb** [comment]
looks like its working in 2022.2.5

**Comment by kloknibor** [comment]
thanks for closing it again :-) Was just about to try it myself.
