### ISSUE TITLE
dishwasher_info set to "OK" while dishwasher is switched off even if cause still persists

### ISSUE THREAD

**Issue by dolodobendan** [HomeAssistant-Mods/home-assistant-miele#105]
The dishwasher has a "problem" (it wants more rinse aid) and reported to HA:

binary_sensor.dishwasher_info -> Problem

When the dishwasher went into standby or whatever, binary_sensor.dishwasher_info was set to "OK". Then I switched it on again and binary_sensor.dishwasher_info again was set to "Problem".

Maybe it's the API, but it would make more sense not to reset it to "OK" when switched off as long the cause still persists. Otherwise, this can only be seen after the dishwasher has finished but before it goes to standby and the time when someone switches it on (and stands right before the dishwasher anyway).

**Comment by kloknibor** [comment]
This is what is returning from the API. I'm sorry but this is something that should be discussed at API level, so please contact miele if you want this changed.

**Comment by dolodobendan** [comment]
I see, thank you!
