### ISSUE TITLE
Sensors for consumables

### ISSUE THREAD

**Issue by nagyrobi** [HomeAssistant-Mods/home-assistant-miele#11]
Would it be possible to add sensors for consumables?
For example in the app the percent status displayed for the Miele UltraPhase 1 and 2 detergent levels is shown:
![kép](https://user-images.githubusercontent.com/1550668/102466511-679f0180-404f-11eb-99ac-d4272246628f.png)
It would be great to have these in Home Assistant because combined with state history, it could be seen the actual consumption over time, something the original app doesn't have.

**Comment by kloknibor** [comment]
Unfortunately, Miele does not open up these levels through their API so there is no way to collect this data. Sorry!
