### ISSUE TITLE
Error on startup HA 2022.5.3

### ISSUE THREAD

**Issue by BloodyusHellus** [HomeAssistant-Mods/home-assistant-miele#115]
After upgrading to HA Core 2022.5.3 (running on RPI 4) I get this error message on startup:

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:109
Integration: miele (documentation, issues)
First occurred: 10:31:19 (1 occurrences)
Last logged: 10:31:19

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 153, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
  File "/config/custom_components/miele/__init__.py", line 109, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

Tried reinstalling the component and rebooting Home Assistant but problem persists.

**Comment by matteocorti** [comment]
Same here

**Comment by BloodyusHellus** [comment]
Problem seems to have fixed itself now.
