### ISSUE TITLE
Entities grouped via device

### ISSUE THREAD

**Issue by c-st** [HomeAssistant-Mods/home-assistant-miele#119]
After setting up the component I have now my Miele appliances available in HomeAssistant. That worked nicely.

However I noticed one oddity and I am wondering whether it's intentional: 
the component created a bunch of entities which are not linked to a device. 

I would have expected a device for each appliance (`device.miele_dishwasher`, `device.miele_oven`, ...). All related entities would then have their `device_id` set and be automatically linked to it. 

This way, one could assign an area to each device and it would implicitly be applied to its entities. 
As of now, as there is no relation between entities, I had to open each entity and manually assign the matching area to of them.

So I am wondering: shouldn't the entity with ID `miele.dishwasher` be a `device.miele_dishwasher` instead and shouldn't all its entities have their respective device set?

**Comment by xZise** [comment]
Hi I was wondering the same, and was looking through the documentation about the [Device Registry](https://developers.home-assistant.io/docs/device_registry_index/) and there it mentions that the integration needs to use config entries (see [Automatic registration through an entity](https://developers.home-assistant.io/docs/device_registry_index/#automatic-registration-through-an-entity)):

> Entity device info is only read if the entity is loaded via a [config entry](https://developers.home-assistant.io/docs/config_entries_index) and the unique_id property is defined.

Anyway I'd also appreciate if this were possible, as I also wanted to assign an area to the entities but didn't wanted to modify each manually.

**Comment by mundschenk-at** [comment]
You might want to have a look at https://github.com/astrandb/miele 😀

**Comment by c-st** [comment]
This other component does just what I want it to. Thanks for the hint! 👍🏼
