### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by nagyrobi** [HomeAssistant-Mods/home-assistant-miele#12]
According to the [API](https://www.miele.com/developer/download.html), a device name can be set. For example (`Upper machine` or `First floor machine`).

This integration seems to [support](https://community.home-assistant.io/t/miele-home-miele-mobile-component/64508/82?u=robi) `miele.action`, and according to the table of actions, it should be possible to set the name of the device like this:
```
{
    'entity_id': 'miele.clothes_dryer',
    'body': {'deviceName': 'Villő'}
}
```
Tried that in Home Assistant, no error and no log entry - but I don't see the name anywhere appearing (restarted HA after running the action). Could it be possible that the `deviceName` field from the API is not being parsed?

**Comment by SteffenWilberg** [comment]
The code seems to supoprt it:
https://github.com/HomeAssistant-Mods/home-assistant-miele/blob/947eb967f1bc7016a298d694f99569fe3a8f34c2/custom_components/miele/sensor.py#L104-L113

But perhaps your Miele device doesn‘t support it. I‘ve tried it with my dishwasher using https://www.miele.com/developer/swagger-ui/swagger.html#/Action/put_devices__deviceId__actions
The response was
```
{
  "message": "DeviceName command is not available for this device"
}
```

**Comment by kloknibor** [comment]
Currently, this integration does not support settings the name by Home assistant. I can take a look to add this in the future if more people would like this? 

For now you can change the name in the app and this should change in Homeassistant with it.

**Comment by SteffenWilberg** [comment]
Interesting, setting the name in the Miele@mobile iOS app (in settings, my Miele devices, your-device, information) worked fine, and HomeAssistant updated to use it just seconds later without even having to reload the page.
I still can‘t get the put action to work on the swagger page mentioned above though.

**Comment by kloknibor** [comment]
Yes the current miele integration just pulls the name from the Miele API and sets the homeassistant device to that name :-) And this is updated (polled) every 5 seconds
