### ISSUE TITLE
Error restart

### ISSUE THREAD

**Issue by mini89** [HomeAssistant-Mods/home-assistant-miele#120]
Every time i restart my hassio i get this error:
Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:174
Integration: miele (documentation, issues)
First occurred: 17 juli 2022 om 18:20:24 (1 occurrences)
Last logged: 17 juli 2022 om 18:20:24

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 152, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 32, in _get_devices_raw
    if await self._session.refresh_token(self.hass):
  File "/config/custom_components/miele/miele_at_home.py", line 165, in refresh_token
    self._token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/miele/miele_at_home.py", line 174, in sync_refresh_token
    return self._session.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) 

I try to get a new key but it won't work i also try to reinstall the intergration but even won't work.
Somebody a idee what to do?

**Comment by woempiej** [comment]
I'm gonna help you wait a minute so I can make a instruction.


Yes it is a issue because the manual as described doesn't work anymore!

--> The Home Assistant Web UI will show you a UI to configure the Miele platform. Follow the instructions to log into the Miele Cloud Service. This will communicate back an authentication token that will be cached to communicate with the Cloud Service.

**Comment by woempiej** [comment]
1. Go to settings --> Integration page --> Select Entities --> Search for miele
![afbeelding](https://user-images.githubusercontent.com/62903344/179575279-ceaece16-97c0-4226-833c-8171b86c3398.png)



2. Click on the configurator.miele_home entitie and then settings icon
![afbeelding](https://user-images.githubusercontent.com/62903344/179575461-cf29dbe2-0610-45df-bd21-70fd508ac8c2.png)

3. Click on the "Link miele account" link
4. You see the below webpage after login

![afbeelding](https://user-images.githubusercontent.com/62903344/179575857-6be2270a-3f39-4f38-ade8-d9cbe715fb21.png)

5. Click on the blue button "I have linked Miele account"


It should worked now. Had the same issue after rolling back via HA backup.

**Comment by mini89** [comment]
Thanks for the quick reaction but the entity configurator.miele_home is not shown in mij list
![Screenshot_20220718-203023.png](https://user-images.githubusercontent.com/59787962/179578659-b0097fa9-2505-43f6-adf3-e405e601e800.png)

**Comment by woempiej** [comment]
Oké, maybe I have not been clear enough

- I have deleted the integration in HACS
- Deleted the cache file via file editor (If you use the optional option like me, then it is an empty file name

![afbeelding](https://user-images.githubusercontent.com/62903344/179579916-d8b90845-7aea-4da0-9f13-197dc3de1b4e.png)
Empty file name:
![afbeelding](https://user-images.githubusercontent.com/62903344/179580886-a7e2b563-7001-4625-95b1-65211a494b19.png)


- Remove the configuration.yaml entries
- Restart HOST, not only HA

Then:
- Reinstall integration in HACS
- Restart HA
- Add the lines in configuration.yaml
- Restart HA

**Comment by woempiej** [comment]
Now I've set it up, its gone on my side 2 (configurator.miele_home)

![afbeelding](https://user-images.githubusercontent.com/62903344/179581839-c303e40e-e4bd-4623-bd6e-17ab935bd5f0.png)

**Comment by mini89** [comment]
Ok that's strange but does the entities still work at your side or not any more?

**Comment by woempiej** [comment]
Yes it does.

![afbeelding](https://user-images.githubusercontent.com/62903344/179599395-d2bf3624-eabc-42ae-8a07-f69d5129334c.png)

It looks like the entity configurator.miele_home goes away after you linked your account.

**Comment by mini89** [comment]
Sorry for not understanding i'm not used to get this deed in the configuration... But I can't find the empty file "cache_path".
In the configuration.yaml i'm not using cache_path

Also on your screenshot is the name of the intergration miele@home in my hassio is the name miele

**Comment by woempiej** [comment]
Oké sorry I cant help then. Maybe i'm wrong about the cache file.
Maybe the code owner can help reading your log file because i'm a complete beginner of understanding that.

**Comment by woempiej** [comment]
Also your app cache can create problems of showing results....

**Comment by woempiej** [comment]
Have the same issue, after restart.

![afbeelding](https://user-images.githubusercontent.com/62903344/180319724-773937ba-f850-4de7-8d19-85cdf90ed9cc.png)

![afbeelding](https://user-images.githubusercontent.com/62903344/180319835-58237b4e-762f-4994-8199-371c7d316771.png)

**Comment by henriklund** [comment]
Check this [post](https://community.home-assistant.io/t/miele-home-miele-mobile-component/64508/415). Look at the post by KennethLavrsen describing the migration path. This solved the issue for me.

**Comment by woempiej** [comment]
Thank you Henriklund. That worked for me!
