### ISSUE TITLE
localize it

### ISSUE THREAD

**Issue by SteffenWilberg** [HomeAssistant-Mods/home-assistant-miele#13]
Some strings are hardcoded, like
https://github.com/HomeAssistant-Mods/home-assistant-miele/blob/df86ba0f453112403e7bf4ddf79c974a12bfeaf0/custom_components/miele/binary_sensor.py#L17-L23
and
https://github.com/HomeAssistant-Mods/home-assistant-miele/blob/df86ba0f453112403e7bf4ddf79c974a12bfeaf0/custom_components/miele/sensor.py#L17-L33
These should be localized. Right now, setting "lang: de" results in a weird mix of German strings provided by the Miele API, and the hardcoded English strings mentioned above. I'd be happy to provide German translations.

**Comment by kloknibor** [comment]
Hmm you do have a point. I will look into this :-)! I will try to translate it myself but I will certainly ask you to double check. Hope to have this done next week! Possibly we should look into adding more translations than the Miele API, might be a good oppertunity to make it more broad.

**Comment by SteffenWilberg** [comment]
For what it’s worth, according to https://www.miele.com/developer/news.html, localization for additional languages is “coming soon”.

**Comment by kloknibor** [comment]
Hmm Intresting I was not aware, thanks! Since it's also a know bug some localizations are missing I think I first want to wait what Miele does with the localizations before I start working on adding our own localizations.

**Comment by kloknibor** [comment]
The following language are now available from the miele API and for now no effor in expanding these will be made:

danish
french
italian
dutch
norwegian
spanish

Will be closed
