### ISSUE TITLE
The following integrations and platforms could not be set up:

### ISSUE THREAD

**Issue by VoetenK** [HomeAssistant-Mods/home-assistant-miele#148]
Home Assistant gives the following error:
The following integrations and platforms could not be set up: miele
I created the credentials on the miele website "https://www.miele.com/f/com/en/register_api.aspx". For this I use the same e-mail address as in the Miele app.
What am I doing wrong?

![Invalid config](https://user-images.githubusercontent.com/27051683/230602582-74f50cb6-cd6e-48e8-b81d-fd747efc948c.png)
![Configuration yaml](https://user-images.githubusercontent.com/27051683/230602889-2827afa3-5f0a-4e7d-b1b7-8a2bccb56499.png)
![custom_components](https://user-images.githubusercontent.com/27051683/230603179-df7143d8-7995-4ae8-a274-5653b8c1b69d.png)

**Comment by geoffm39** [comment]
getting the same issue.  I already had the integration setup and working for months, but after the latest patch it stopped working

**Comment by Coffee0297** [comment]
same issue here.. have been working for 4 months or so, and no i get error

**Comment by Coffee0297** [comment]
Heres what my log gives me:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 152, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 32, in _get_devices_raw
    if await self._session.refresh_token(self.hass):
  File "/config/custom_components/miele/miele_at_home.py", line 165, in refresh_token
    self._token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/miele/miele_at_home.py", line 174, in sync_refresh_token
    return self._session.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) ```

**Comment by geoffm39** [comment]
> Heres what my log gives me:
> 
> ```
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
>     result = await task
>   File "/config/custom_components/miele/__init__.py", line 152, in async_setup
>     data_get_devices = await client.get_devices(lang)
>   File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
>     home_devices = await self._get_devices_raw(lang)
>   File "/config/custom_components/miele/miele_at_home.py", line 32, in _get_devices_raw
>     if await self._session.refresh_token(self.hass):
>   File "/config/custom_components/miele/miele_at_home.py", line 165, in refresh_token
>     self._token = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/miele/miele_at_home.py", line 174, in sync_refresh_token
>     return self._session.refresh_token(
>   File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
>     self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
>   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
>     self.token = parse_token_response(body, scope=scope)
>   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
>     validate_token_parameters(params)
>   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
>     raise_from_error(params.get('error'), params)
>   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
>     raise cls(**kwargs)
> oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) ```
> ```
same logs here

**Comment by Coffee0297** [comment]
Seems like this is not maintained, i have switched to this one and it works flawlessly.
https://github.com/astrandb/miele
Maybe hacks should mark this one as inactive
