### ISSUE TITLE
Automatically refresh access token

### ISSUE THREAD

**Issue by myhomeiot** [HomeAssistant-Mods/home-assistant-miele#15]
After about a month integration failed to start with error message in the log about access token expiration. Is it possible to add automatic token renewal? This probably can help [Miele API Token refresh and Logout](https://www.miele.com/developer/swagger-ui/swagger.html#/Token%20refresh%20and%20Logout).

**Comment by kloknibor** [comment]
There actually is already automatic token renewal but it seems to fail sometimes. I was already planning to look into this but I will add it into the list on github as well.

**Comment by kloknibor** [comment]
Just released a fix on the dev repo... So currently testing : 79b16889905bd37f4990ca615844eeb71d5036a4

**Comment by kloknibor** [comment]
So in the end I think I found a nice fix. with this commit : 4722143f049fa9d845dffcabfa2df294fa0a800f the only thing I'm not sure about is if we can still refresh it just after the token expired or if we need to time this like some hours in advance.  This should be an easy fix if that is the case but if it's not needed I rather leave it like this :-)! Feel free to try the dev version and see if your token gets refrshed on time.

**Comment by kloknibor** [comment]
A possible fix for this has been released. When in 30 days there are no issues with the token anymore this will be closed

**Comment by myhomeiot** [comment]
> A possible fix for this has been released. When in 30 days there are no issues with the token anymore this will be closed

Thanks I will update this issue in February

**Comment by kloknibor** [comment]
My token has been automatically refreshed a couple of days ago. I hope yours as well?

**Comment by myhomeiot** [comment]
Confirmed, my token refreshed as well.

**Comment by kloknibor** [comment]
Thanks for confirming :-)!
