### ISSUE TITLE
Invalid config The following integrations and platforms could not be set up:  miele.sensor  -> HA 2023.5 Beta

### ISSUE THREAD

**Issue by andreasbuff** [HomeAssistant-Mods/home-assistant-miele#150]
Hello 

Miele integartion is a great thing! I had the miele integration working, without any problems. Now I have installted HA 2023.5 Beta-Release and it stoped working. 

=> "Invalid config, The following integrations and platforms could not be set up:

       miele.sensor ([Show logs](http://192.168.1.163:8123/config/logs?filter=miele.sensor))" 
=> Error log is: "2023-05-03 10:21:29.629 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform miele.sensor: Platform not found (cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py))."

Can anyone help please ? Thanks

**Comment by RA42HA** [comment]
Same here.
Why this issue has been closed?
