### ISSUE TITLE
Additional info in Washing Machine Info/Failure and Clothes Dryer Info/Failure

### ISSUE THREAD

**Issue by myhomeiot** [HomeAssistant-Mods/home-assistant-miele#17]
Integration provides 4 binary sensors with device class **problem**:
- binary_sensor.washing_machine_info
- binary_sensor.washing_machine_failure
- binary_sensor.clothes_dryer_info
- binary_sensor.clothes_dryer_failure

Is it possible to add message attribute to these sensors which will shows that machines shows at screen?

**Comment by kloknibor** [comment]
Sorry could you explain your request further? It's not 100% clear for me yet... Thanks in advance!

**Comment by myhomeiot** [comment]
For example **binary_sensor.washing_machine_info** becomes **on** and washing machine shown at screen the message "Cartridge 1 almost empty. Only a few more programmes are possible" or "Align the washing machine". Will be great to have this message as attribute of binary_sensor.washing_machine_info.

I'm not sure if it's possible to get this information from API but Miele@mobile shows some of them.

**Comment by kloknibor** [comment]
Miele unfortunately does not supply this info with their public API so as such I am unable to implement this at the current time.
