### ISSUE TITLE
Entity inconsistency between HA and Miele API documentation

### ISSUE THREAD

**Issue by stefferber** [HomeAssistant-Mods/home-assistant-miele#20]
thx for this excellent Miele integration ;-)

While setting up my lovelance UI for my Miele G6865 Dishwasher I observed that the following entities are available in Home Assistant:
 
<img width="1014" alt="Bildschirmfoto 2021-01-25 um 17 52 07" src="https://user-images.githubusercontent.com/5459845/105751688-a9707100-5f46-11eb-9bfc-93b66743dd62.png">

In addition these attributes are available:
<img width="402" alt="Bildschirmfoto 2021-01-25 um 17 52 59" src="https://user-images.githubusercontent.com/5459845/105751736-b7be8d00-5f46-11eb-9277-5f375f0d7433.png">
<img width="403" alt="Bildschirmfoto 2021-01-25 um 17 54 13" src="https://user-images.githubusercontent.com/5459845/105751754-ba20e700-5f46-11eb-8e11-286585310f4e.png">

the following `entities` do not get any data, every:

```
sensor.geschirrspuler_target_temperature_0
sensor.geschirrspuler_temperature_0
sensor.geschirrspuler_temperature_1
sensor.geschirrspuler_temperature_2
```
which is consistent with the [official Miele API documentation](https://www.miele.com/developer/capabilities.html)

<img width="380" alt="Bildschirmfoto 2021-01-25 um 19 56 42" src="https://user-images.githubusercontent.com/5459845/105752409-8a261380-5f47-11eb-810d-3d19af0f92fe.png">

Looks like the Home Assistant Miele integration should not set up `sensor` for these `temperature`  in this case.

In addition, I observed that some [Miele dishwashers report energy (german: energie) and water (german: wasser) usage](https://www.reddit.com/r/homeassistant/comments/k8hjuz/my_first_attempt_for_a_dishwasher_card_what/). With additional sensors

```
sensor.geschirrspuler_wasser
sensor.geschirrspuler_energie
```

My dishwasher collects the same information and shows this on the dishwasher display. But it does not show up in the official Miele API description neither in the Home Assistant integration. 

Any idea how we can correct this?

**Comment by kloknibor** [comment]
Hi, 

thanks for your input! The problem is that the Miele API always returns all sensors and does not tell us what sensor a device actually is able to use. It does however return a certain value when the sensor is not in use at that specific time. The problem is that this sensor later can become active and then it will not show up in home assistant since the sensors are made when home assistant boots. 

There are 3 ways that can possible solve this :
- Miele needs to change their API and tell us what capabilities a device actually have (preferred way).
- We need to create a sensor in home assistant as soon as an actual correct value is received (homeassistant does not like this, I tried to create this functionality but it became to complex for me).
- We need to start logging all the capabilities per machine ourselves (At this moment this does not sound like a desirable solution to me)

For your energy usage of the dishwasher, if it does not show up on the Miele API it can't be shown in Homeassistant. There are more values missing from the miele API though.

**Comment by kloknibor** [comment]
Actually what could do is using this table to make the amount of unused sensor less : https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf that doesn't seem to hard, I'll try to implement this.

**Comment by kloknibor** [comment]
So I just created a filter based on the documentation of Miele. Which can be found here: 9f23e6b2746f0b251a5a4fc1a8127a398a98989f

Annoyingly enough the documentation of Miele is incorrect... According to the document with device capabilities no target temprature is available for washing machines. However mine does give a target temprature!

I will try to reach out to miele to find out if more is wrong... If you want you can try the update from the dev branch

**Comment by kloknibor** [comment]
Also replying on these sensors :

sensor.geschirrspuler_wasser
sensor.geschirrspuler_energie

The one you link to are not made by this integration. However the data is available under the status sensor as can be seen here: 

Just use those attributes. I will clean those up a little bit more as well.

![image](https://user-images.githubusercontent.com/10560390/105868728-c3698c80-5ff6-11eb-9f24-5ada0741e088.png)

**Comment by kloknibor** [comment]
Ifyou do however want to make it it's own sensor you can create a template sensor, instructions can be found here :https://www.home-assistant.io/integrations/template

**Comment by stefferber** [comment]
Thx @kloknibor for your quick and clear posts. If you need some help programming or testing "just assign" a task to me ;-) Regarding the sensor template, this is what I did for better access to `Progress`, I hope I did it right:

```
sensor:
  - platform: template
    sensors:
      geschirrspuler_progress:
        value_template: "{{ state_attr('sensor.geschirrspuler_status', 'progress')| float }}"
        unit_of_measurement: '%'
        icon_template: 'mdi:clock'
        friendly_name: Geschirrspüler Progress
```

**Comment by stefferber** [comment]
There was an [update information](https://www.miele.com/developer/news.html) I did not really understand:

```
added: information to state endpoint
  * ecoFeedback - supported by Washing machine, Tumble dryer, Dishwasher and Washer dryer
```
where did the API change?

**Comment by kloknibor** [comment]
@stefferber the state endpoint appearantly. We added the eco feedback to the integration 2 months ago already though... This was done by a PR from another dev.

**Comment by stefferber** [comment]
Can you explain what this is for?

**Comment by kloknibor** [comment]
Miele added this part to their API I think : Weird thing is we already added it a little bit before the news. 
 ],
      "ecoFeedback": {
        "currentWaterConsumption": {
          "unit": "string",
          "value": 0
        },
        "currentEnergyConsumption": {
          "unit": "string",
          "value": 0
        },
        "waterforecast": 0,
        "energyforecast": 0
      },

**Comment by stefferber** [comment]
Cool - how to access this information with Home Assistant Integration?
This does not show up in my dishwasher status, but I see it in your washing machine status...

**Comment by stefferber** [comment]
looks like my dishwasher does not fetch it; looks like the first ` if ` is `false`:
```
        if "ecoFeedback" in device_state and device_state["ecoFeedback"] is not None:
            if "currentWaterConsumption" in device_state["ecoFeedback"]:
                attributes["currentWaterConsumption"] = device_state["ecoFeedback"][
                    "currentWaterConsumption"
                ]["value"]
                attributes["currentWaterConsumptionUnit"] = device_state["ecoFeedback"][
                    "currentWaterConsumption"
                ]["unit"]
            if "currentEnergyConsumption" in device_state["ecoFeedback"]:
                attributes["currentEnergyConsumption"] = device_state["ecoFeedback"][
                    "currentEnergyConsumption"
                ]["value"]
                attributes["currentEnergyConsumptionUnit"] = device_state[
                    "ecoFeedback"
                ]["currentEnergyConsumption"]["unit"]
            if "waterForecast" in device_state["ecoFeedback"]:
                attributes["waterForecast"] = device_state["ecoFeedback"][
                    "waterForecast"
                ]
            if "energyForecast" in device_state["ecoFeedback"]:
                attributes["energyForecast"] = device_state["ecoFeedback"][
                    "energyForecast"
                ]
```
what is the best way to debug what is really in `device_state`?

**Comment by kloknibor** [comment]
@stefferber it seems unlikely that this statement is false since Miele sends the "ecoFeedBack" with all queries, since it does load it for me in the status component of my washingmachine.

If you want you can send me the credentials/bearer over e-mail and I can check for you in my testing environment.

Or if you want to do it yourself I use the logging function and add a bunch of debug logs to test in my system and see what is happening. Most likely there are better ways but I'm not a prof programmer.

**Comment by stefferber** [comment]
Thx for your kind offer. Which eMail can I use to send the credentials?

**Comment by kloknibor** [comment]
You should have received an -email from me ;-) email with the dieferbers domain.

**Comment by kloknibor** [comment]
Hi @stefferber , 

like discussed over e-mail it seems your Dishwasher does not support the eco feedback currently since the Miele API does not return this info for your dishwasher. 

Below you can see on the left the response of the Miele API for my supported Washingmachine while it was off and on the right when it was turned on.

![image](https://user-images.githubusercontent.com/10560390/106521324-5d8d7100-64de-11eb-8df2-166e7a8409d3.png)

You can see that when my washing machine is on it reports back information about the "ecoFeedback" (it is not null). Hass than also puts this data in the state of the entity.

For your dishwasher however it remains null for both off and on state:

![image](https://user-images.githubusercontent.com/10560390/106521454-8ca3e280-64de-11eb-9f42-b8a368e6fd11.png)


the complete API response of your dishwasher while it is on can be seen below. As you can see we can see in the API it was operational and returned null for the ecoFeedback.

```
{
  "censored": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 7,
        "value_localized": "Dishwasher"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "censored",
        "fabIndex": "64",
        "techType": "censored",
        "matNumber": "censored",
        "swids": [
          "censored",
          "censored",
          "censored"
        ]
      },
      "xkmIdentLabel": {
        "techType": "censored",
        "releaseVersion": "02.72"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 38,
        "value_localized": "QuickPowerWash",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 5,
        "value_localized": "In use",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 2,
        "value_localized": "Automatic programme",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 1794,
        "value_localized": "Pre-wash",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        6
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "temperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": false,
        "mobileStart": false
      },
      "light": 0,
      "elapsedTime": [
        0,
        1
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  }
}
````

So probably Miele does not support this option for your Dishwasher (at this time?). Not much I can do about that, unfortunately.

**Comment by stefferber** [comment]
@kloknibor thank you so much for your "debugging session". It never could do it so quickly. Now I will check with Miele why the Eco data is missing in the API - it is shown on the dishwasher display.
If have one more idea and observation: Maybe it depends on the dishwasher program as in QuickWash the eco data is also not shown on the display.

**Comment by kloknibor** [comment]
@stefferber please feel free to try different programs yourself. If the api sends the response it will show under the status of your dishwasher like mentioned before. I am not affiliated with miele so I have no idea what dishwashers are supported and which are not. I just double checked if it might be a mistake within the integration I maintain and that was not the case :-)

**Comment by stefferber** [comment]
Tried several Miele dishwasher programs: still does not show up via the API. But the Miele App gets the data. This means that there must be a different API for this dishwasher. The attached image shows it with the German terms "Energie" = energy and "Wasser" = water. 
![IMG_5004](https://user-images.githubusercontent.com/5459845/108364842-cf5ffd00-71f6-11eb-93c8-b51edb8528f9.PNG)

**Comment by kloknibor** [comment]
@stefferber Yes most likely Miele uses an own private API internally for their apps. Unfortunately, we don't have access to this...  So we will just have to wait till Miele adds functionality like this. Feel more than free to contact them with a request ofcourse :-)!

**Comment by stefferber** [comment]
Thx - I am still waiting for Miele to respond. The keep us waiting for 2 weeks now...

**Comment by stefferber** [comment]
Now I got the official Miele response to the question in this post. I have the feeling that this does not really help. I will post their German and my translation in the next two posts.

**Comment by stefferber** [comment]
<img width="1437" alt="Bildschirmfoto 2021-02-28 um 18 12 45" src="https://user-images.githubusercontent.com/5459845/109426993-9989f800-79f0-11eb-9186-340284dece15.png">

**Comment by stefferber** [comment]
<img width="1488" alt="Bildschirmfoto 2021-02-28 um 18 18 35" src="https://user-images.githubusercontent.com/5459845/109427169-685df780-79f1-11eb-9794-174800d390cb.png">

**Comment by stefferber** [comment]
Today, I tested also the Swagger https://www.miele.com/developer/swagger-ui/swagger.html#/Information and also received 

```
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
```
looks very much like a Miele bug.

**Comment by kloknibor** [comment]
What they basically tell you is what data is to be expected in the 3 different modes (off, programmed and running). However for your particular machine Miele does not seem to support the public API yet.... Untill they add the support for your machine this integration can not work either I'm afraid.

**Comment by stefferber** [comment]
This week I received the information from developer@miele.com that the Miele 3rd Party API for ecoFeedback objects is not supported for dishwashers of the G6xxx generation.
