### ISSUE TITLE
TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by gigatexel** [HomeAssistant-Mods/home-assistant-miele#22]
I've just installed the component according to the instructions and added my credentials.
A token is generated and stored, so that works fine.

When initializing the integration, the error log lists:
'''
Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 145, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 53, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable
'''

**Comment by kloknibor** [comment]
It seems like you are not using the latest version, how did you install and what is your version in HACS?

**Comment by gigatexel** [comment]
Using HACS 1.10.1 and no alert for more recent version of integration. Clicking update information for this repository does nothing.

**Comment by kloknibor** [comment]
I just tried a fresh install and can't seem to be able to reproduce this issue. We have seen an issue like this before which was caused by hidden sensors/entities. This should be solved in recent versions. Do you have by any chance any hidden sensors?

**Comment by gigatexel** [comment]
No luck. I checked my Entities page in HA and nothing is hidden.

**Comment by kloknibor** [comment]
would you be ok if i take a look at your install?

**Comment by gigatexel** [comment]
No problem, how? GH does not support DM's :-)

**Comment by kloknibor** [comment]
@gigatexel normally you can find an e-mail but it seems you have your mail hidden. You can reach me at : robinkolk@msn.com

**Comment by kloknibor** [comment]
It seems this issue is a problem on the autohentication side with miele. The Miele API fails to return anything. We tried to renew the token but it seemed re-logging in did not work. For this reason @gigatexel is contacting @miele for support. Untill than this issue is on hold.

**Comment by kloknibor** [comment]
@gigatexel any news from Miele?

**Comment by gigatexel** [comment]
02/02 I've sent an email to partner.developer@miele.com, but no answer from there.
08/02 I've sent an email to info@miele.be and they have reset my password. Offcourse that does not fix it and on 10/02 I've explained them the issue again.

If someone has an other email adress for Miele Dev's, please let me know.

**Comment by kloknibor** [comment]
Could you maybe send me your e-mail and password over mail. Just to see if I can get any further with it... But no other mails are known by me...

**Comment by gigatexel** [comment]
Dag Robin,

Login: stijnadamstijn@gmail.com
pass: robin123

client_id: b7fe7c98-8d86-43d4-8123-0e9c7a15e894
client_secret: Pfpxem8grxlYa6WiK2ERYq7CzRXWS5de

Op vr 12 feb. 2021 om 12:25 schreef Robin Kolk <notifications@github.com>:

**Comment by kloknibor** [comment]
@gigatexel you (accidentally)  replied on github with your password so I would remove this post and change the credentials. I am able to login to your account in the app. So it seems there is no problem with your account, but however it does seem to mismatch with the client_id and client_secret.

**Comment by gigatexel** [comment]
So I should start over again?

**Comment by kloknibor** [comment]
Well atleast try to retrieve a new client ID and client secret. Since the app does seem able to use your account just fine.

**Comment by gigatexel** [comment]
Magic.
Repeating the procedure has now (for the first time) given me a new client-id.
Works perfectly now.
