### ISSUE TITLE
Again: assertion Error

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele#28]
ahh. there we go again:
![image](https://user-images.githubusercontent.com/70005749/107248767-e94d5300-6a32-11eb-8907-2df7af243c8d.png)
Assertion error returned in version 5973df2

**Comment by kloknibor** [comment]
I will try to take a look later... That part of the code shouldn't have any changes...

**Comment by kloknibor** [comment]
@FransHalsjes did you by any chance hide a binary sensor recently :P? The issue you have know is in the binary sensor component this has not been touched this year yet and the problem you had last time was in the sensor component. I only solved the hiding issue in the sensor component.

I will write a fix for you hopefully sometime this week. In the meantime unhide the binary sensor you hid.

So this is not an issue that returned, it is a new issue ;-)!

**Comment by FransHalsjes** [comment]
Hi @kloknibor . Indeed, i made several sensors hidden (as they are of no meaning, such as Cooktop_remaining_time). I have now made all sensors visible again and re-started HA. Error is gone.

**Comment by kloknibor** [comment]
The sensors we implemented a fix for in the past which should still work. This has not been merged to the binary sensors (yes/no) yet. So the sensors you should be able to hide but the binary sensors not for now

**Comment by kloknibor** [comment]
Solved with : 33db0e0cf504118621493ad1287e18bab407ecfa
