### ISSUE TITLE
Update infos for installation

### ISSUE THREAD

**Issue by Bascht74** [HomeAssistant-Mods/home-assistant-miele#3]
See https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/

Could you change the installation instructions from hassbian to hass.io?

Seb

**Comment by kloknibor** [comment]
The readme page is gonna be changed completely and hopefully sometime soon we will be available in the dafault HACS repo and the custom installation off the requirement should not needed anymore! 

But we will still leave some documentation for manual installation. If you wanna contribute on updating the documentation at this point than please feel free!

**Comment by nagyrobi** [comment]
A quick note, on my hassio install I didn't have to do anything with the prerequisites. It seems to already have `requests_oauthlib` by default.
All I did was just to copy `miele` folder to `custom_components`.

**Comment by kloknibor** [comment]
That is correct, I have done a PR to homassistant wheel which makes the prerequisites being included with hass :-)!

**Comment by kloknibor** [comment]
Commit 947eb96 - updates installation instructions. We are now part of the defaults from HACS for even simpler installation :-)!
