### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [HomeAssistant-Mods/home-assistant-miele#5]
*Sorry for not following the issue template*

If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by kloknibor** [comment]
All PR's are welcome, so yes feel free to contribute!

**Comment by KTibow** [comment]
Thanks! Mind answering the questions in the bullet points?

**Comment by kloknibor** [comment]
Auto formatting is just for indents and enters? Sorry, I'm not too familiar with CI yet. Also, can you explain to me the advantages and disadvantages of packaged and independent?

**Comment by KTibow** [comment]
Disadvantage of independent is that you probably won’t get any updates given my workload amount. Disadvantage of packaged is that sometimes hassfest doesn’t work for a random reason, and I might accidentally send out a change that breaks stuff.

**Comment by kloknibor** [comment]
Let's go for packaged for now than :-)! Thanks!
