### ISSUE TITLE
Light support in oven appliances

### ISSUE THREAD

**Issue by emilp333** [HomeAssistant-Mods/home-assistant-miele#51]
Hi,

According to the API docs ovens and combi ovens should support the light action. 
I tried to modify light.py to add the device type and HA now gets the light entity for the appliance. It even shows the correct status if the light is on or off when toggled on the appliance itself but pressing it in HA does not work.

Have you fiddled around with this yourself? Any clues?

**Comment by kloknibor** [comment]
I unfortunately don't have a miele device with a controllable light. Just a miele washing machine :-) But what I understand is that U got it working to show the current state but you can just not control it?

Either the action call you did not implement correctly or miele just doesn't support this to be controlled remotely (their devices all have a wide range of supported actions... Only way to 100% check it is to go to their swagger API and request the following:

https://www.miele.com/developer/swagger-ui/swagger.html#/Action/get_devices__deviceId__actions

**Comment by kloknibor** [comment]
stale
