### ISSUE TITLE
Error during setup of component miele

### ISSUE THREAD

**Issue by pille89** [HomeAssistant-Mods/home-assistant-miele#56]
Hello, please excuse me, I know the error has already been edited here. However, I do not get this fixed. I have already tested my account through here: https://www.miele.com/developer/swagger-ui/swagger.html# I get my devices displayed. What else could it be?
Am grateful for any help. 

Kind regards

```
Logger: homeassistant.setup
Source: helpers/network.py:123
First occurred: 18:25:14 (1 occurrences)
Last logged: 18:25:14

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 121, in async_setup
    callback_url = "{}{}".format(get_url(hass), AUTH_CALLBACK_PATH)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

**Comment by kloknibor** [comment]
It seems it might have to do with DNS that is unable to resolve the URL or something (haven't checked the code fully, just a first assumption). 

How is your installation done? VM, docker, hass.io, hassbian?

**Comment by swavans** [comment]
I got the same error. I'm running hass.io with DuckDNS. How I solved this was specifying the internal and external url in the Configuration => General part of HA

**Comment by Dazula** [comment]
Same error here - also DuckDNS hass.io
@swavans I am new to HA are you able to elaborate on how to define the URLS and where.   Thanks

**Comment by swavans** [comment]
You can enter those under configuration => general

**Comment by Dazula** [comment]
@swavans Sorted thanks.  me being dumb - I was originally trying to look for somewhere to edit in files.

**Comment by kloknibor** [comment]
good you guys sorted it, but indeed the callback url should be correct. Closing for now. If still having issues let me know. But not fully a integration issue.
