### ISSUE TITLE
[Feature Request] Support for AutoDos (PowerDisk, Ultraphase 1 & 2) fill levels.

### ISSUE THREAD

**Issue by DrBlackRat** [HomeAssistant-Mods/home-assistant-miele#66]
It would be nice if I could see / use the AutoDos fill levels for my washing machine / dishwasher, so that I won't have to use the Miele App for that.

**Comment by kloknibor** [comment]
This is unfortunately not supported by the API, if you want this function please contact miele. Issue will be closed.
