### ISSUE TITLE
[Feature request] Auto-DOS levels

### ISSUE THREAD

**Issue by carpii** [HomeAssistant-Mods/home-assistant-miele#71]
Some washing machine models have consumables for the Auto-DOS feature

It would be great to see those sensors pulled into HA, so you can set alerts when the Ultraphase liquids are getting low.
These stats are available in the Miele app

Thanks for your work on this integration!

**Comment by catadiel** [comment]
Unfortunately, the [actual public developer](https://www.miele.com/developer/swagger-ui/swagger.html#/Eventing/get_devices__deviceId__events) API doesn't provide this information.
So neither this integration can.

You could write to their support e-mail to suggest this addition to the state object as they do with _batteryLevel_.
maybe if this is a common request they will enrich the data provided in the next API version.

Until then there's nothing we can do.

**Comment by carpii** [comment]
Ok, thats a shame. I'll petition Miele, thanks for the reply!
