### ISSUE TITLE
Added appliance not showing up

### ISSUE THREAD

**Issue by ifuchs** [HomeAssistant-Mods/home-assistant-miele#72]
I have this working with a Miele dishwasher; however, when I added a dryer in the app I can’t get HA to see it (works fine in the app). What do I need to do to see this appliance?

**Comment by kloknibor** [comment]
Can you please go to this website : https://www.miele.com/developer/swagger-ui/swagger.html#/Action/get_devices__deviceId__actions

click authorize and login and than click /devices -> try it out -> execute and post the reply you got over here? Thanks!

**Comment by kloknibor** [comment]
stale for to long, if u have new information please provide this and we can re-open the issue.
