### ISSUE TITLE
Did not recieve Miele devices

### ISSUE THREAD

**Issue by gigatexel** [HomeAssistant-Mods/home-assistant-miele#74]
For a long time now, the error below shows up frequently in HA.

Would it be an option to:

- Increase timeout for the call to Miele Cloud? Maybe Miele Cloud sometiems is just too slow?
- Try multiple times before raising an error?

```
Logger: custom_components.miele
Source: custom_components/miele/__init__.py:171
Integration: Miele@home (documentation, issues)
First occurred: October 14, 2021, 14:18:43 (4 occurrences)
Last logged: October 14, 2021, 18:50:55

Did not receive Miele devices
```

**Comment by kloknibor** [comment]
I am not sure why this would be considered an issue to show this error. When there is a problem with the network and the devices are not refreshed because of this I think this error makes sense? Personally I never have this issue on my own network connection.

**Comment by gigatexel** [comment]
Is someone else experiencing this?

Still having this error:

```
Logger: custom_components.miele
Source: custom_components/miele/__init__.py:173
Integration: Miele@home ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: May 9, 2022, 09:37:14 (973 occurrences)
Last logged: 08:06:41

Did not receive Miele devices
```
