### ISSUE TITLE
No devices are added

### ISSUE THREAD

**Issue by Usever** [HomeAssistant-Mods/home-assistant-miele#77]
Once setup is complete I can see entities added, but no real devices are assembled from the entities.

Is this OK and I should build devices manually out of entities?

**Comment by kloknibor** [comment]
indeed different entities are created with all the available data. there is a miele device which will just contain some device info, but not sensor data.

**Comment by mundschenk-at** [comment]
I think @Usever meant [HA devices](https://developers.home-assistant.io/docs/device_registry_index/), while you were talking about the `miele.<devicename>` _entity_.

**Comment by KarmCraft** [comment]
So, how was this solved? I am having the same experience.
