### ISSUE TITLE
Add ProgramID

### ISSUE THREAD

**Issue by SteffenWilberg** [HomeAssistant-Mods/home-assistant-miele#8]
Washing machines, Tumbly dryers, dishwashers etc. support ProgramID.
``` json
"state": {
      "ProgramID": {
        "value_raw": 28,
        "value_localized": "Economy",
        "key_localized": "Program Id"
      },
```

The value of „value_localized“ can also be „SaniPlus“, „Sensor Wash“, „Pots & Pans“, „QuickPowerWash“, „China & Crystal“, „Normal“, „Extra Quiet“ etc., so that‘s more interesting than the „programType“ property, which always has „Automatic Program“.

**Comment by kloknibor** [comment]
Hi @SteffenWilberg I just took a second look at the Miele API but I can't seem to find this ProgramID on this API list. Could you either mail me your .miele token (preferred) or send me/post here the complete output after calling the /devices endpoint from here : https://www.miele.com/developer/swagger-ui/swagger.html#/Information/get_devices I'm open to implement this and add this state as a sensor to Home assistant

**Comment by SteffenWilberg** [comment]
It‘s mentioned on https://www.miele.com/developer/capabilities.html and
https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf

Here‘s the swagger output:
```json
{
  "000103956939": {
    "ident": {
      "type": {
        "key_localized": "Devicetype",
        "value_raw": 7,
        "value_localized": "Dishwasher"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "000103956939",
        "fabIndex": "63",
        "techType": "G6895-W",
        "matNumber": "10345070",
        "swids": [
          "3893",
          "20201",
          "20124",
          "4055",
          "20221",
          "20181",
          "3273"
        ]
      },
      "xkmIdentLabel": {
        "techType": "EK039W",
        "releaseVersion": "02.72"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 28,
        "value_localized": "Economy",
        "key_localized": "Program Id"
      },
      "status": {
        "value_raw": 3,
        "value_localized": "Program selected",
        "key_localized": "State"
      },
      "programType": {
        "value_raw": 2,
        "value_localized": "Automatic program",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 1792,
        "value_localized": "",
        "key_localized": "Phase"
      },
      "remainingTime": [
        3,
        35
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "temperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "signalInfo": true,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": false,
        "mobileStart": false
      },
      "light": 0,
      "elapsedTime": [
        0,
        0
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spinning Speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Power Level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  }
}

**Comment by kloknibor** [comment]
I think I prefer to put the ProgramID under a status sensor. Instead of it's own programID text sensor. Was there a specific reason you want this to be a seperate sensor?

**Comment by SteffenWilberg** [comment]
Yes, a separate sensor shows up everywhere in HomeAssistant like History and Logbook, so I can gather which programs run how often, or when a certain program was run for the last time. This seems much more interesting like sensors like the door status, or the failure sensor (which doesn‘t tell you which failure), or the 4 temperature sensors which don‘t display anything for my dishwasher.

**Comment by kloknibor** [comment]
Allright, than I understand the reason. In that case I'll leave it like this. I'll try to merge it to master before the end of the year :-)! Thanks for your effort!

**Comment by kloknibor** [comment]
PR is pulled into the main branch
