### ISSUE TITLE
After update to 0.9.0 the binary_sensor.washing_machine_door sensor is mising

### ISSUE THREAD

**Issue by SalkinDK** [HomeAssistant-Mods/home-assistant-miele#80]
First of all, thx so much for all your work.

As the titel states.
After i have updated to the 0.9.0 version i have lost multiple sensors.
The most important being the door sensor.

Anyone experience the same?

**Comment by kloknibor** [comment]
I just checked and for me the washing machine door is still present and updating as expected.

What other sensors are missing?

**Comment by SalkinDK** [comment]
After updating to 2021.11 and a couple of restarts the sensors are back. 
sorry for taking your time.
