### ISSUE TITLE
Cooker hood light dimmable

### ISSUE THREAD

**Issue by ArowonA** [HomeAssistant-Mods/home-assistant-miele#83]
On the Miele app i have the option of dimming the light, is this something that could be added in the future?

Thanks
![IMG_0139](https://user-images.githubusercontent.com/13576154/144070110-af6e9b4f-24bf-453f-8479-ef7c65dfa45b.PNG)

**Comment by kloknibor** [comment]
According to : https://www.miele.com/developer/capabilities.html this seems not possible yet with their API. Closed.

**Comment by ArowonA** [comment]
Ok thanks, it shows on that list that it supports "colors" - no idea what that would do, so if I get a chance I will have a play to see if that alters the brightness at all.

**Comment by kloknibor** [comment]
I unfortunately only have a Miele washing machine myself. If with testing with the swagger API (which can also be found at the same website) you can control the brightness of the lights I would be more than happy to implement this.
