### ISSUE TITLE
Entity implements device_state_attribute

### ISSUE THREAD

**Issue by keimaster** [HomeAssistant-Mods/home-assistant-miele#89]
First of all, thank you for your great work on this integration.
When implemented (and working as intended) I get the following error message in my logs. I do not know how to handle this, and it does not affect the entity for me, but thought you might get something out of me notifying you.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 11:30:56 (2 occurrences)
Last logged: 11:30:56

Entity miele.tumble_dryer (<class 'custom_components.miele.MieleDevice'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.tumble_dryer_status (<class 'custom_components.miele.sensor.MieleStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by raph521** [comment]
I've noticed other customer components that had the same warning as of Home Assistant Core 2021.12.

They've resolved it by replacing `device_state_attributes` with `extra_state_attributes`. 

For example:
https://github.com/custom-components/sensor.sonarr_upcoming_media/commit/ecf06f08c2cc2b35d1462ca900102ba487c3ed46

**Comment by kloknibor** [comment]
See #82 , this PR is already merged into the dev branch :-) Thanks for the input though!
