### ISSUE TITLE
Water and energy usage always 0

### ISSUE THREAD

**Issue by eikowagenknecht** [HomeAssistant-Mods/home-assistant-miele#92]
I'm using this integration with two devices:
- Dishwasher G6865-W
- Washer Dryer WTH720

Neither reports anything other than a "0" for energy or water usage, neither while running nor before or after:
![image](https://user-images.githubusercontent.com/1475672/147782509-c91f0b2b-3e5f-4253-8296-5f5bae0b6b3e.png)

Is this device dependent? Then the sensors should not be created for devices without the capability. Or is this some other problem? Logs seem fine to me, no warnings or errors related to this integration.

**Comment by eikowagenknecht** [comment]
Disabling the useless sensors triggers another error by the way:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:526
First occurred: 01:44:58 (4 occurrences)
Last logged: 01:44:58

Entity sensor.eg_kueche_waschtrockner_energieverbrauch is incorrectly being triggered for updates while it is disabled. This is a bug in the miele integration
Entity sensor.eg_kueche_waschtrockner_wasserverbrauch is incorrectly being triggered for updates while it is disabled. This is a bug in the miele integration
Entity sensor.eg_kueche_geschirrspueler_energieverbrauch is incorrectly being triggered for updates while it is disabled. This is a bug in the miele integration
Entity sensor.eg_kueche_geschirrspueler_wasserverbrauch is incorrectly being triggered for updates while it is disabled. This is a bug in the miele integration
```

**Comment by mundschenk-at** [comment]
The Miele API is currently broken, even for supposedly supported devices, energy consumption is reported as `0` by the API. Also, the capabilities itself would need to be device dependent (i.e. `ecoFeedback` via API is not supported on the `6xxx` series of dishwashers). The integration currently maps device _types_ to capabilities. I don't think there is a way to derive the actual capabilities from the API unfortunately.

**Comment by eikowagenknecht** [comment]
Thanks for the feedback, closing this as it seems it's just an API issue on the miele side. I disabled the entities in the meantime.
