### ISSUE TITLE
Dishwasher door is always reported as closed

### ISSUE THREAD

**Issue by dolodobendan** [HomeAssistant-Mods/home-assistant-miele#96]
Thank you for this integration!

The only thing I encountered so far is that the dishwasher door is always reported as closed.

**Comment by kloknibor** [comment]
Please check on https://www.miele.com/developer/swagger-ui/ if your door is reported open and closed. If this is not the case that means it will be a problem with Miele or your device. if you do see a difference please let me know.

**Comment by dolodobendan** [comment]
I didn't actually figure out how to do that.* But: The door status is reported correctly in the Miele app.

*) Authorization etc. worked fine, I have the deviceID but really don't know where to look. This is what I get for

GET /devices/{fabnumber}/state

```
{
  "ProgramID": {
    "value_raw": 6,
    "value_localized": "Auto",
    "key_localized": "Program name"
  },
  "status": {
    "value_raw": 3,
    "value_localized": "Programme selected",
    "key_localized": "status"
  },
  "programType": {
    "value_raw": 0,
    "value_localized": "Program",
    "key_localized": "Program type"
  },
  "programPhase": {
    "value_raw": 1792,
    "value_localized": "",
    "key_localized": "Program phase"
  },
  "remainingTime": [
    2,
    38
  ],
  "startTime": [
    0,
    0
  ],
  "targetTemperature": [
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    }
  ],
  "temperature": [
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    }
  ],
  "signalInfo": false,
  "signalFailure": false,
  "signalDoor": false,
  "remoteEnable": {
    "fullRemoteControl": true,
    "smartGrid": false,
    "mobileStart": false
  },
  "ambientLight": null,
  "light": null,
  "elapsedTime": [
    0,
    0
  ],
  "spinningSpeed": {
    "unit": "rpm",
    "value_raw": null,
    "value_localized": null,
    "key_localized": "Spin speed"
  },
  "dryingStep": {
    "value_raw": null,
    "value_localized": "",
    "key_localized": "Drying level"
  },
  "ventilationStep": {
    "value_raw": null,
    "value_localized": "",
    "key_localized": "Fan level"
  },
  "plateStep": [],
  "ecoFeedback": {
    "currentWaterConsumption": {
      "unit": "l",
      "value": 8
    },
    "currentEnergyConsumption": {
      "unit": "kWh",
      "value": 0.6
    },
    "waterForecast": 0.3,
    "energyForecast": 0.45
  },
  "batteryLevel": null
}
```

Since `"value_localized": "Auto",` changes depending on what I have selected, I guess I'm doing something right here. But I don't see anything besides  `"signalDoor": false, ` regarding the door. And signalDoor stays the same, no matter if the door is open or closed (Clear & Execcute for each request).

Thank you for your help!

**Comment by kloknibor** [comment]
"signalDoor": false is the correct variable to take a look at. 
Unfortunately Miele uses their private API which doesn't correspond with their public API we can use. Since your value of signalDoor doesn't change this means it an problem in the public Miele API and I unfortunately can't help you. Please contact miele.
