### ISSUE TITLE
TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by scapman** [HomeAssistant-Mods/home-assistant-miele#98]
Hello.
The integration has been working perfectly for months.
Since a few days it isn't working anymore and I get thi error:

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:52
Integration: miele (documentation, issues)
First occurred: 11:57:11 (1 occurrences)
Last logged: 11:57:11

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 150, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 52, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable

Configuration yaml:

miele:
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Version:
Homeassistant: core-2021.12.9
Operating SysteM: Home Assistant OS 7.1
Supervisor: supervisor-2021.12.2
Component Miele: 0.9.1

I have reinstalled, deleted the hidden token file, reconfigured and created a new client_secret at Miele Developer site.
Nothing has helped

How can I solve?
Thanks

**Comment by geni0602** [comment]
same here #95 nothing helped so far.
token deleted 
reinstalled
new client_secret

**Comment by Polimac** [comment]
Same here

deleted everything
got new clientid and secret

tested with swagger and it is working (get devices see all of them)

but on HA after adding configuration for clientid and secret i got this

> [homeassistant.setup] Error during setup of component miele
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
> result = await task
> File "/config/custom_components/miele/__init__.py", line 150, in async_setup
> data_get_devices = await client.get_devices(lang)
> File "/config/custom_components/miele/miele_at_home.py", line 52, in get_devices
> for home_device in home_devices:
> TypeError: 'coroutine' object is not iterable


Version | core-2022.2.7
Host Operating System | Home Assistant OS 7.4
supervisor-2022.01.1
HACS: 
Integration version: | 1.22.0
Frontend version: | 20220206093206

**Comment by sebltm** [comment]
This fixed it for me https://github.com/HomeAssistant-Mods/home-assistant-miele/pull/108

**Comment by kloknibor** [comment]
#108 is merged into the dev branche, please check it and see if it resolved your issue. thanks to @sebltm.
